#!/usr/bin/env perl
use strict; use warnings;
use v5.14;

use FindBin;
use lib "$FindBin::Bin/../lib";

use RaumZeitLabor::Status::Update;

RaumZeitLabor::Status::Update->run;

# vim: set ts=4 sw=4 sts=4 expandtab:
